[package]
name = "reactor-tests"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type=["cdylib"]

[dependencies]
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "8f34a0279a4ac361024b4bb51299fa0e38e0f520" }
